apiVersion: v1
kind: Secret
metadata:
  name: cb-example-auth
type: Opaque
data:
  username: YWRtaW4=              # admin
  password: YWRtaW4xMjM=          # admin123
---
apiVersion: couchbase.com/v2
kind: CouchbaseBucket
metadata:
  name: default
spec:
  memoryQuota: 256Mi
---
apiVersion: couchbase.com/v2
kind: CouchbaseCluster
metadata:
  name: cb-example
spec:
  image: couchbase/server:7.6.0
  security:
    adminSecret: cb-example-auth
  networking:
    exposeAdminConsole: true
    adminConsoleServices:
    - data
  buckets:
    managed: true
  cluster:
    dataServiceMemoryQuota: 256Mi
    indexServiceMemoryQuota: 256Mi     
    queryServiceMemoryQuota: 256Mi    
    searchServiceMemoryQuota: 256Mi    
    eventingServiceMemoryQuota: 256Mi 
    analyticsServiceMemoryQuota: 1024Mi 
  servers:
  - size: 2
    name: all_services
    services:
    - data
    - index
    - query
    - search
    - eventing
    - analytics
    resources:
        requests:
          cpu: "500m"
          memory: "2Gi"  
        limits:
          cpu: "1"
          memory: "4Gi"    